### ISSUE TITLE
Zipkin pipeline fail

### ISSUE THREAD

**Issue by Farkal** [OutThereLabs/actix-web-opentelemetry#32]
If i try to use zipkin pipeline instead of jaeger it fail with: `Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.`

Code:
```toml
[dependencies]
actix-web = "3.2"
actix-web-opentelemetry = "0.7"
opentelemetry-zipkin = "0.7"
```

```rust
use actix_web::{get, web, App, HttpServer, Responder};
use actix_web_opentelemetry::RequestTracing;

#[get("/{id}/{name}/index.html")]
async fn index(web::Path((id, name)): web::Path<(u32, String)>) -> impl Responder {
    format!("Hello {}! id:{}", name, id)
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    opentelemetry_zipkin::new_pipeline()
            .install()
            .expect("pipeline install error");
    HttpServer::new(|| App::new().service(index).wrap(RequestTracing::new()))
        .bind("127.0.0.1:8080")?
        .run()
        .await
}
```

**Comment by jtescher** [comment]
@Farkal it should work if you use the following workaround currently:

```toml
[dependencies]
# ...
opentelemetry-zipkin = { version = "0.7", features = ["reqwest-client"], default-features = false }
reqwest = "0.10"
```

**Comment by jtescher** [comment]
If you want to use things currently, you can specify the http client when you start the zipkin pipeline:

```toml
[dependencies]
actix-web = "3.2"
actix-web-opentelemetry = "0.7"
opentelemetry = { version = "0.9", features = ["reqwest"] }
opentelemetry-zipkin = { version = "0.7", default-features = false }
reqwest = "0.10"
```

```rust
use actix_web::{get, web, App, HttpServer, Responder};
use actix_web_opentelemetry::RequestTracing;

#[get("/{id}/{name}/index.html")]
async fn index(web::Path((id, name)): web::Path<(u32, String)>) -> impl Responder {
    format!("Hello {}! id:{}", name, id)
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    opentelemetry_zipkin::new_pipeline()
        .with_http_client(reqwest::Client::new())
        .install()
        .expect("pipeline install error");
    HttpServer::new(|| App::new().service(index).wrap(RequestTracing::new()))
        .bind("127.0.0.1:8080")?
        .run()
        .await
}
```
